# Generated by Django 3.2.17 on 2023-07-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0016_lticonfiguration_lti_1p3_proctoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiagslineitem',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ltiagslineitem',
            name='deployment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ltiagslineitem',
            name='oidc_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
