# Generated by Django 3.2.23 on 2025-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0017_add_ags_multi_tenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiagslineitem',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
